### ISSUE TITLE
After Checking out from version control it cannot find method runProguard()

### ISSUE THREAD

**Issue by rodydavis** [AndroidExamples/fragment-navigation#1]
Error:(15, 0) Could not find method runProguard() for arguments [false] on BuildType_Decorated{name=release, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=null, embedMicroApp=true, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.
<a href="openFile:/Users/rodydavis/Documents/GitHub/fragment-navigation/app/build.gradle">Open File</a>

**Comment by hanscappelle** [comment]
depends on Android Studio version, updated code to work with latest version
